version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: odontologiadeluz:latest
    container_name: odontologiadeluz-web
    restart: unless-stopped
    
    # Puerto interno del contenedor
    expose:
      - "80"
    
    # Variables de entorno
    environment:
      - NODE_ENV=production
    
    # Healthcheck para monitoreo
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Recursos (ajustar según tu VM)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Labels para Easypanel
    labels:
      - "easypanel.enable=true"
      - "easypanel.name=odontologiadeluz"
      - "easypanel.domain=odontologiadeluz.cl"
      - "easypanel.port=80"
      - "easypanel.https=true"
      - "easypanel.https.redirect=true"
